version: "3.2"
services:
  chargingstation:
    build: charging-station
    ports:
      - "3000:3000"
    networks:
      - backend

  frontend:
    build: frontend
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - chargingstation

networks:
  backend:
